[package]
name = "poly-arb-quoters"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dotenvy = "0.15"
ethers = { version = "2", features = ["abigen", "rustls"] }
tokio = { version = "1", features = ["full"] }
